### PR TITLE
Default to current project, Glob for increased priority of listing, etc

### PR DESCRIPTION
**Pull request by claytonrcarter**
There's a handful of updates in this that I've been using for weeks without incident.  I made the updates for Netbeans because that's what I use; I'm not familiar with JEdit so wouldn't know where to start.

### CODE REVIEW

**Comment by mjomble** [comment]
@claytonrcarter hey, any news? :D

**Comment by mjomble** [comment]
I took a bit of time to familiarize myself with NetBeans module development and got this project to build.

I also submitted pull request #21 with some useful config files and released version 1.1 with Clayon's changes on my fork: https://github.com/mjomble/off-plugin/releases

@sickill Now that I can build the plugin, I wouldn't mind being the new maintainer. I can't make any promises about resolving open issues and I don't use JEdit, but I could tweak the NetBeans plugin a little and try to make it easier for others to contribute.

**Comment by sickill** [comment]
@mjomble awesome! I added you as a collaborator. You have my blessing ;)

**Comment by mjomble** [comment]
Cool! Do you also still have the access details for the plugin in the NetBeans plugin portal?
http://plugins.netbeans.org/plugin/16495/open-file-fast

Not sure what options there are for collaborating, if any.

**Comment by sickill** [comment]
I have access details. Just logged in there. There is no option to collaborate.
But I'm happy to send you the credentials if you'd like to be able to upload new versions there. I don't use this account for anything else.

**Comment by mjomble** [comment]
Sounds good, you can send the credentials to mjomble@gmail.com

**Pull request merged**
